# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARE_DIR: prepare
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  featurize_dir: features
  featurize_train_data: train.pkl
  featurize_test_data: test.pkl
source_data:
  data_dir: data
  data_file: data.xml
  
